language: python
python:
  - "3.9"
  - "3.12"
install:
  - pip install -U pip
  - pip install .
  - pip install -U pylint pytest pytest-cov
script:
  - >
    pytest
    --cov=sentry_stack_checker
    --cov-fail-under=100
